# Generated by Django 5.0 on 2024-01-27 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_customer_address'),
        ('product', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_items',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_items', to='product.product'),
        ),
    ]
