# Generated by Django 5.0 on 2024-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_expected_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('I', 'Individuals'), ('G', 'Groups'), ('O', 'Others')], default='O', max_length=1),
        ),
    ]
