# Generated by Django 5.0 on 2024-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('A', 'Placed'), ('B', 'Confirmed'), ('P', 'Dispatched'), ('F', 'Failed'), ('C', 'Cancel'), ('R', 'Return'), ('D', 'Delivered')], default='P', max_length=1),
        ),
    ]
