# Generated by Django 5.0 on 2024-03-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_delivery_boy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('A', 'Placed'), ('B', 'Confirmed'), ('P', 'Packed'), ('O', 'On the way'), ('F', 'Failed'), ('C', 'Cancel'), ('R', 'Return'), ('D', 'Delivered')], default='P', max_length=1),
        ),
    ]
