# Generated by Django 5.0 on 2024-03-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Failed'), ('P', 'Pending'), ('R', 'Returned')], default='P', max_length=1),
        ),
    ]
