# Generated by Django 5.0 on 2024-03-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_options_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Failed'), ('P', 'Pending'), ('R', 'Refunded')], default='P', max_length=1),
        ),
    ]
