# Generated by Django 5.0 on 2024-02-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryboy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='area',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='city',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='locality',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='pan_card_number',
            field=models.CharField(default='xxxxxxxxxx', max_length=12),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='state',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='zipcodes',
            field=models.CharField(default='00000000', max_length=100),
        ),
    ]
