# Generated by Django 5.0 on 2024-01-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('H', 'Home'), ('C', 'Current'), ('O', 'Other')], default='C', max_length=1),
        ),
    ]
