# Generated by Django 5.0 on 2023-12-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentbyuser',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='paymentbyuser',
            name='razorpay_order_id',
            field=models.CharField(default='defaultid', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentbyuser',
            name='razorpay_payment_id',
            field=models.CharField(default='rzpymntid', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentbyuser',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
