# Generated by Django 5.0 on 2023-12-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_paymentbyuser_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentbyuser',
            name='timestamp',
        ),
    ]
