# Generated by Django 5.0 on 2024-01-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymentbyuser_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentbyuser',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='paymentbyuser',
            name='payment_status',
        ),
    ]
