# Generated by Django 5.0 on 2024-01-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercart',
            options={'ordering': ['-created_at']},
        ),
    ]
